version: '3'

services:
  app-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=app

  contract-db:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=contract

  partner-db:
    image: mysql:latest
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=partner


  adminer:
    image: adminer
    ports:
      - "9000:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql1
    depends_on:
      - app-db
      - contract-db
      - partner-db